/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FooterComponent {
    }
    interface HeaderComponent {
    }
    interface HomeComponent {
    }
}
declare global {
    interface HTMLFooterComponentElement extends Components.FooterComponent, HTMLStencilElement {
    }
    var HTMLFooterComponentElement: {
        prototype: HTMLFooterComponentElement;
        new (): HTMLFooterComponentElement;
    };
    interface HTMLHeaderComponentElement extends Components.HeaderComponent, HTMLStencilElement {
    }
    var HTMLHeaderComponentElement: {
        prototype: HTMLHeaderComponentElement;
        new (): HTMLHeaderComponentElement;
    };
    interface HTMLHomeComponentElement extends Components.HomeComponent, HTMLStencilElement {
    }
    var HTMLHomeComponentElement: {
        prototype: HTMLHomeComponentElement;
        new (): HTMLHomeComponentElement;
    };
    interface HTMLElementTagNameMap {
        "footer-component": HTMLFooterComponentElement;
        "header-component": HTMLHeaderComponentElement;
        "home-component": HTMLHomeComponentElement;
    }
}
declare namespace LocalJSX {
    interface FooterComponent {
    }
    interface HeaderComponent {
    }
    interface HomeComponent {
    }
    interface IntrinsicElements {
        "footer-component": FooterComponent;
        "header-component": HeaderComponent;
        "home-component": HomeComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "footer-component": LocalJSX.FooterComponent & JSXBase.HTMLAttributes<HTMLFooterComponentElement>;
            "header-component": LocalJSX.HeaderComponent & JSXBase.HTMLAttributes<HTMLHeaderComponentElement>;
            "home-component": LocalJSX.HomeComponent & JSXBase.HTMLAttributes<HTMLHomeComponentElement>;
        }
    }
}
