/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BenefitsNavigator {
    }
    interface FooterComponent {
    }
    interface HeaderComponent {
    }
    interface HomeComponent {
    }
    interface MainComponent {
    }
}
declare global {
    interface HTMLBenefitsNavigatorElement extends Components.BenefitsNavigator, HTMLStencilElement {
    }
    var HTMLBenefitsNavigatorElement: {
        prototype: HTMLBenefitsNavigatorElement;
        new (): HTMLBenefitsNavigatorElement;
    };
    interface HTMLFooterComponentElement extends Components.FooterComponent, HTMLStencilElement {
    }
    var HTMLFooterComponentElement: {
        prototype: HTMLFooterComponentElement;
        new (): HTMLFooterComponentElement;
    };
    interface HTMLHeaderComponentElement extends Components.HeaderComponent, HTMLStencilElement {
    }
    var HTMLHeaderComponentElement: {
        prototype: HTMLHeaderComponentElement;
        new (): HTMLHeaderComponentElement;
    };
    interface HTMLHomeComponentElement extends Components.HomeComponent, HTMLStencilElement {
    }
    var HTMLHomeComponentElement: {
        prototype: HTMLHomeComponentElement;
        new (): HTMLHomeComponentElement;
    };
    interface HTMLMainComponentElement extends Components.MainComponent, HTMLStencilElement {
    }
    var HTMLMainComponentElement: {
        prototype: HTMLMainComponentElement;
        new (): HTMLMainComponentElement;
    };
    interface HTMLElementTagNameMap {
        "benefits-navigator": HTMLBenefitsNavigatorElement;
        "footer-component": HTMLFooterComponentElement;
        "header-component": HTMLHeaderComponentElement;
        "home-component": HTMLHomeComponentElement;
        "main-component": HTMLMainComponentElement;
    }
}
declare namespace LocalJSX {
    interface BenefitsNavigator {
    }
    interface FooterComponent {
    }
    interface HeaderComponent {
    }
    interface HomeComponent {
    }
    interface MainComponent {
    }
    interface IntrinsicElements {
        "benefits-navigator": BenefitsNavigator;
        "footer-component": FooterComponent;
        "header-component": HeaderComponent;
        "home-component": HomeComponent;
        "main-component": MainComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "benefits-navigator": LocalJSX.BenefitsNavigator & JSXBase.HTMLAttributes<HTMLBenefitsNavigatorElement>;
            "footer-component": LocalJSX.FooterComponent & JSXBase.HTMLAttributes<HTMLFooterComponentElement>;
            "header-component": LocalJSX.HeaderComponent & JSXBase.HTMLAttributes<HTMLHeaderComponentElement>;
            "home-component": LocalJSX.HomeComponent & JSXBase.HTMLAttributes<HTMLHomeComponentElement>;
            "main-component": LocalJSX.MainComponent & JSXBase.HTMLAttributes<HTMLMainComponentElement>;
        }
    }
}
